### PR TITLE
PRD-861: Feat(config) - Added config methods

### PR DESCRIPTION
**Pull request by adlenafane**

### CODE REVIEW

**Comment by kaesonho** [comment]
thanks @adlenafane , the code looks good to me, however I'm thinking if users should access ga plugin instance directly and do whatever they need?

for example 

``` js
var instance = ReactI13nGoogleAnalytics.getInstance();
instance.command( // do whatever they need
```

**Comment by adlenafane** [comment]
@kaesonho Actually today we're writing stuff like the following in our code:

``` javascript
  ReactI13n.getInstance().execute('command', {
    commandName: 'send',
    arguments: ['event', category, action, label, value]
  });
```

**Comment by kaesonho** [comment]
good point @adlenafane, so seems like we should reuse `ReactI13n.getInstance().execute('command',`  to do these config methods, may I know if we add these functions, how are we going to use them?

**Comment by adlenafane** [comment]
@kaesonho sorry you're right, I haven't given any context.
We were using [angulartics](http://angulartics.github.io/) when our platform was in Angular, today we're fulling migrating to react and we wanted to used `react-i13n` in the same spirit which is a wrapper to our trackers.
The idea is to have one method to call to handle several trackers. So in our case we use GA, Mixpanel and a home made one. In this context we're glad to use the pageview / click solution and we were missing the configuration we had with Angulartics [see here](https://github.com/angulartics/angulartics/blob/master/src/angulartics.js#L55)

**Comment by kaesonho** [comment]
I see, it's clearer now  :)

I'm fine with this change, could you add a section in README for those config methods?

**Comment by adlenafane** [comment]
@kaesonho Doc udpated!

**Comment by kaesonho** [comment]
nice, thanks @adlenafane  :)

**Comment by kaesonho** [comment]
it's published https://github.com/kaesonho/react-i13n-ga/releases/tag/v0.2.6  

as we are still in 0.x mode, I just did a patch version bump.  we can find sometime to update it to be 1.x.

**Pull request merged**
